- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Ensure fail2ban is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Deploy nginx-sensitive jail configuration
  ansible.builtin.template:
    src: nginx-sensitive.local.j2
    dest: /etc/fail2ban/jail.d/nginx-sensitive.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Deploy nginx-sensitive filter
  ansible.builtin.template:
    src: nginx-sensitive.conf.j2
    dest: /etc/fail2ban/filter.d/nginx-sensitive.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
