- name: Update packages
  hosts: all
  become: true
  roles:
    - { role: update-packages, tags: ["update"] }
    - { role: nginx-ssl, tags: ["nginx", "ssl"] }
    - { role: firewalld, tags: ["firewalld"] }
    - { role: fail2ban, tags: ["fail2ban"] }
    - { role: postgresql, tags: ["postgresql"] }
    - { role: rabbitmq, tags: ["rabbitmq"] }
    - { role: redis, tags: ["redis"] }
    - { role: python_project, tags: ["python_project"] }
