- name: Update packages
  hosts: all
  become: true
  roles:
    - { role: update-packages, tags: ["update"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: firewalld, tags: ["firewalld"] }
    - { role: fail2ban, tags: ["fail2ban"] }
    - { role: postgresql, tags: ["postgresql"] }
    - { role: rabbitmq, tags: ["rabbitmq"] }
