
---
postgresql_version: 16

domain_name: example.com
certbot_email: s.b.nikuliny@gmail.com

nginx_server_name: "ferum-dsg.duckdns.org"
nginx_document_root: "/var/www/html"

postgresql_user: appuser
postgresql_password: apppass
postgresql_database: appdb

rabbitmq_user: myuser
rabbitmq_password: mypassword
rabbitmq_vhost: myvhost


project_name: mailing_bot_aiogram
project_repo: "https://github.com/gooodh/AiogramAlchemyTemp.git"
project_path: "/opt/{{ project_name }}"
python_version: "3.12"
